FROM python:3.12.7-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

COPY . .


ENV PORT=8000
ENV DB_USER=admin
ENV DB_PASSWORD=123456789
ENV DB_HOST=ecomtech_postgres
ENV DB_PORT=5432
ENV DB_NAME=postgres_ecomtech


EXPOSE 8000

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload"]